[package]
name = "iced-gauges"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
time = { version = "0.3", features = ["local-offset"] }

[dependencies]
iced = { version = "0.8", features = ["canvas", "tokio", "debug"] }
